-- NOTE: bufferline.nvim removed - using built-in buffer management
-- Native alternatives:
-- - :ls or :buffers - List all buffers
-- - :bnext or :bn - Next buffer
-- - :bprevious or :bp - Previous buffer
-- - :buffer N or :b N - Go to buffer N
-- - :bdelete or :bd - Delete current buffer
-- - Tab and Shift-Tab mapped in keymaps.lua for navigation
-- - <leader>1-9 mapped for direct buffer access
-- Benefits: No plugin overhead, native buffer management, faster startup
return {}